### ISSUE TITLE
feat: create the end of the chain of responsibility for creating Shape(s)

### ISSUE THREAD

**Issue by khoa-l** [Fall23csc509/CodeVillage#52]
- Extend the ShapeChainEnd abstract class in a PutShapesChainEnd class

**Comment by buk0vec** [comment]
Impl details:
- We have finished making our neighborhoods and shapes!
- Starting with the top-level neighborhood wrapper, take all Shapes for JavaEntities and the Neighborhood and put them in CanvasData. Note that the top-level neighborhood doesn't have a Neighborhood since it's not a real logical neighborhood and we aren't drawing a box around it.
- Repeat this for all subneighborhoods
